#!/bin/bash

mysql <<EOFMYSQL
use bkj011;

CREATE TABLE STUDENTS(
STUDENTID int,
STUDENTNAME varchar(30) NOT NULL,
MAJOR varchar(30) NOT NULL,
PRIMARY KEY (STUDENTID)
);

CREATE TABLE JOBS(
JOBID int,
COMPANYNAME varchar(30) NOT NULL,
JOBTITLE varchar(30) NOT NULL,
SALARY int UNSIGNED NOT NULL CHECK (SALARY > 0),
DESIREDMAJOR varchar(30) NOT NULL,
PRIMARY KEY (JOBID)
);

CREATE TABLE APPLICATIONS(
STUDENTID int,
JOBID int,
PRIMARY KEY (STUDENTID, JOBID),
FOREIGN KEY (STUDENTID) REFERENCES STUDENTS (STUDENTID),
FOREIGN KEY (JOBID) REFERENCES JOBS (JOBID)
);

CREATE TABLE HIRES(
EMPLOYEEID int,
JOBID int,
LOCATION varchar(30) NOT NULL,
STARTDATE date NOT NULL,
PRIMARY KEY (EMPLOYEEID, JOBID),
FOREIGN kEY (EMPLOYEEID) REFERENCES STUDENTS(STUDENTID),
FOREIGN KEY (JOBID) REFERENCES JOBS (JOBID)
);

INSERT INTO STUDENTS VALUES (0, 'Bob Marley', 'Agribusiness');
INSERT INTO STUDENTS VALUES (1, 'Adam Sandler', 'Theater');
INSERT INTO STUDENTS VALUES (2, 'John Gauch', 'Computer Science');
INSERT INTO STUDENTS VALUES (3, 'Colin Goolsby', 'Physics');

INSERT INTO JOBS VALUES (1000, 'Ronald McDonald Inc.', 'Class Clown', 2, 'Theater');
INSERT INTO JOBS VALUES (1001, 'Umbrella Corp.', 'Product Tester', 100000, 'Computer Science');
INSERT INTO JOBS VALUES (1002, 'OSU Corp.', 'OSU Player', 420, 'Physics');

INSERT INTO APPLICATIONS VALUES (1, 1000);
INSERT INTO APPLICATIONS VALUES (0, 1001);
INSERT INTO APPLICATIONS VALUES (2, 1001);
INSERT INTO APPLICATIONS VALUES (3, 1002);

DELETE FROM APPLICATIONS WHERE STUDENTID = 2 AND JOBID = 1001;
INSERT INTO HIRES VALUES (2, 1001, 'Remote', '2023-04-23');
DELETE FROM APPLICATIONS WHERE STUDENTID = 3 AND JOBID = 1002;
INSERT INTO HIRES VALUES (3, 1002, 'Queens, NY', '2023-04-23');


DESC STUDENTS;
DESC JOBS;
DESC APPLICATIONS;
DESC HIRES;

EOFMYSQL
