/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 11
#define YY_END_OF_BUFFER 12
static yyconst short int yy_accept[180] =
    {   0,
        0,    0,   12,   10,    7,    7,   10,   10,   10,    5,
       10,    9,    9,    9,    9,    8,    8,    8,    7,    0,
        0,    0,    4,    0,    0,    0,    5,    0,    9,    0,
        0,    0,    9,    9,    9,    9,    8,    8,    8,    0,
        5,    0,    4,    5,    0,    0,    0,    0,    6,    9,
        9,    9,    8,    8,    0,    0,    0,    0,    5,    5,
        0,    0,    9,    0,    9,    8,    2,    0,    5,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    0,    0,    0,    2,    2,
        0,    3,    0,    0,    2,    2,    0,    0,    0,    2,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    8,    8,    8,    8,    1,
        1,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
       17,   18,    8,   19,   20,   20,   21,   22,   20,   23,
       20,   24,   20,   20,   20,   20,   20,   20,   20,   25,
       20,   20,   20,   26,   20,   20,   20,   20,   20,   20,
        1,    1,    1,    8,   27,    1,   28,   29,   29,   29,

       30,   31,   32,   33,   29,   29,   29,   34,   29,   35,
       36,   37,   29,   29,   38,   39,   29,   29,   29,   29,
       29,   29,    8,    1,    8,   40,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    2,    2,    1,    2,    3,    2,    4,    4,    5,
        6,    7,    8,    9,   10,    1,    4,    1,   11,   12,
       12,   12,   12,   12,   12,   12,   13,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   13
    } ;

static yyconst short int yy_base[200] =
    {   0,
        0,    0,  547,  643,   39,   43,  527,   35,   36,   50,
       57,   85,  517,   27,   42,   98,   45,   46,   71,  525,
        0,   67,   38,  527,   68,   69,   91,  526,    0,  101,
        0,  102,    0,  497,   55,   72,    0,   84,   84,  523,
      103,  105,  126,  132,  519,  514,  512,  520,  643,  495,
      101,  116,  132,  123,    0,  135,  136,  137,  147,  507,
      515,  160,  505,  506,  497,  488,  489,  153,  155,  157,
      177,  480,  174,  489,  479,  167,    0,  483,  215,  219,
      236,  231,  268,  157,  466,    0,  166,  417,  243,  306,
      201,  248,    0,  203,  229,  236,  402,  236,  214,  209,

      259,  251,  154,    0,    0,  216,  381,  263,  243,  268,
      272,  233,  379,  266,  280,  244,    0,  279,  376,  304,
      374,  367,  292,  285,  325,  307,    0,    0,   68,  312,
      316,  320,  278,  338,  280,  376,  414,    0,  181,    0,
      279,  296,  312,  453,    0,  318,  356,    0,    0,    0,
        0,  394,  431,  470,  194,  435,  359,  309,  437,  311,
      441,    0,  444,  317,  439,  447,  393,  453,  444,  371,
      178,  456,  153,  107,  137,  474,  408,  472,  643,  493,
      504,  515,  525,  530,  540,   39,  552,  564,  576,  581,
      585,  589,  596,  603,  607,  614,  619,  623,  630

    } ;

static yyconst short int yy_def[200] =
    {   0,
      179,    1,  179,  179,  179,  179,  180,  180,  180,  181,
      182,  181,   12,   12,   12,   12,   16,   16,  179,  180,
      183,  180,  180,  179,  180,  180,   12,  179,   12,  182,
      184,  182,   12,   12,   12,   12,   16,   16,   16,  183,
      179,  180,  180,   12,  179,  184,  179,  185,  179,   12,
       12,   12,   16,   16,  186,  180,  180,  180,   12,  179,
      185,  185,   12,  179,   12,   16,  186,  180,  180,  180,
      179,  179,  179,  179,  179,  180,   71,  187,   71,   71,
      188,   71,   71,   83,  189,  190,  180,  187,   71,  188,
       83,   90,   83,   83,   83,   83,  189,  189,  190,  180,

       83,   83,  189,  191,  192,  180,  179,   83,  189,  191,
      193,  180,  179,  189,  194,  180,  195,  189,  196,  194,
      179,  180,  195,  189,  196,  179,  197,  198,  189,  179,
      197,  199,  189,  179,  189,  179,  179,  134,  179,  134,
      134,  134,  189,  136,  144,  144,  144,  137,  137,  137,
      137,  137,  137,   71,  134,  134,  189,  144,  144,  137,
      137,  154,  134,  134,  189,  144,  144,  137,  137,  179,
      134,  189,  144,  137,  189,  189,  189,  189,    0,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179

    } ;

static yyconst short int yy_nxt[684] =
    {   0,
        4,    5,    6,    5,    5,    7,    4,    7,    8,    4,
        7,    9,    4,   10,    4,   11,    7,    4,    4,   12,
       12,   13,   14,   15,   12,   12,    7,   16,   16,   16,
       17,   16,   18,   16,   16,   16,   16,   16,   16,    7,
       19,   19,   19,   19,   19,   19,   19,   19,   22,   23,
       67,   23,   35,   21,   21,   20,   21,   20,   20,   24,
       25,   26,   30,   27,   28,   35,   20,   36,   21,   31,
       35,   36,   19,   19,   19,   19,   20,   25,  133,   51,
       36,   42,   43,   38,   39,   21,   21,   21,   98,   20,
       20,   51,   20,   20,  179,   20,   20,   52,   33,  179,

       24,   20,   26,   21,   44,   28,  179,  179,   51,   52,
       52,   20,   24,  179,   47,   64,   41,   48,   56,   49,
       53,  107,   54,   21,   20,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   57,   65,   43,
       51,   24,   58,   26,   21,   59,   64,   51,   68,   69,
       70,  176,   51,   21,   21,   21,   24,   98,   26,   53,
       59,   71,   71,   58,   71,  179,   57,  107,   69,   66,
       76,   21,   72,   21,   98,   21,  100,   73,   77,   77,
       87,   77,   96,   78,   21,   21,   47,   79,  109,   48,
       80,   49,  170,   81,  154,   96,   82,   82,   82,   83,

       84,   82,   82,   79,   82,   82,   82,   83,   82,   84,
       82,   82,   82,   82,   82,   82,   90,   90,  163,   90,
       91,   91,  106,   91,  104,  105,   82,   21,   96,  112,
      163,   72,   91,   91,   21,   91,   73,   92,   92,   82,
       92,   96,   78,   72,   91,   91,  116,   91,   73,   92,
       92,   21,   92,  101,   82,   72,   98,  122,   93,   94,
       73,  102,   21,   98,  179,  101,   93,   82,   94,   91,
       91,  103,   91,  107,  102,  101,   82,  107,  104,  105,
       72,  114,  104,  105,   82,   73,   98,  101,   82,   82,
      104,  105,  119,   95,  121,  118,  108,   82,   98,   98,

       98,   82,  127,  128,  155,   98,   95,   90,   90,  143,
       90,  135,   78,  124,  104,  105,  119,  155,  121,  119,
      130,  156,   81,  129,  119,  130,  127,  128,   93,   94,
      127,  128,   98,  166,  156,  168,   93,  119,   94,   91,
       91,  163,   91,  158,   78,  166,  157,  168,  136,  128,
      137,  138,  139,  163,   81,   73,  158,  140,  140,  140,
      141,  142,  140,  140,   79,  140,  140,  140,  141,  140,
      142,  140,  140,  140,  140,  140,  140,   90,   90,   98,
       90,  159,   78,  113,  154,   21,   79,  126,  119,  144,
      165,  117,   81,  113,  159,  145,  145,  145,  146,  147,

      145,  145,   79,  145,  145,  145,  146,  145,  147,  145,
      145,  145,  145,  145,  145,   91,   91,  166,   91,  160,
       78,  178,   98,   89,  148,  149,  137,  150,   98,  166,
       81,   73,  160,  151,  151,  151,  152,  153,  151,  151,
      148,  151,  151,  151,  152,  151,  153,  151,  151,  151,
      151,  151,  151,  149,   91,   91,  161,   91,  170,   98,
      164,  107,  167,  136,  128,   72,  169,  107,  168,  161,
       73,   91,   91,  164,   91,  167,   98,  172,  177,  169,
      168,  171,  137,  162,  173,  178,   98,   73,  175,   89,
      174,   86,   98,   85,   98,   20,   20,   73,   20,   20,

       55,   20,   64,   20,   20,   20,   29,   29,   29,   29,
       29,   64,   29,   29,   29,   29,   29,   32,   75,   74,
      179,   28,   32,   32,   63,   61,   32,   40,   40,   49,
       40,   49,   60,   40,   55,   50,   40,   40,   46,   45,
       41,   46,   62,   21,   34,   21,  179,  179,   62,  179,
      179,   62,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   80,  179,  179,  179,  179,
      179,  179,   80,  179,  179,   80,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   99,
      179,  179,   99,  110,  179,  179,  110,  111,  179,  179,

      111,  115,  115,  179,  115,  179,  179,  115,  120,  120,
      120,  120,  120,  179,  120,  123,  179,  179,  123,  125,
      125,  125,  125,  179,  179,  125,  125,  131,  179,  179,
      131,  132,  179,  179,  132,  134,  134,  179,  134,  179,
      179,  134,    3,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179
    } ;

static yyconst short int yy_chk[684] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    6,    6,    6,    6,    8,    9,
      186,   23,   14,    8,    9,   10,   23,   10,   10,   10,
       10,   10,   11,   10,   10,   14,   10,   15,   10,   11,
       17,   18,   19,   19,   19,   19,   10,   22,  129,   35,
       15,   25,   26,   17,   18,   22,   25,   26,  129,   10,
       12,   35,   12,   12,   12,   12,   12,   36,   12,   12,

       27,   12,   27,   12,   27,   27,   30,   32,   38,   39,
       36,   12,   41,   30,   32,   51,   41,   32,   42,   32,
       38,  174,   39,   42,   12,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   43,   51,   43,
       52,   44,   44,   44,   43,   44,   53,   54,   56,   57,
       58,  175,   52,   56,   57,   58,   59,  175,   59,   54,
       59,   62,   62,   68,   62,   62,   69,  173,   69,   53,
       70,   68,   62,   69,  103,   70,   87,   62,   71,   71,
       76,   71,   84,   71,   87,   76,   73,   71,  103,   73,
       71,   73,  171,   71,  139,   84,   71,   71,   71,   71,

       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   79,   79,  155,   79,
       80,   80,  100,   80,   99,   99,   91,  100,   94,  106,
      155,   80,   82,   82,  106,   82,   80,   81,   81,   91,
       81,   94,   81,   82,   89,   89,  112,   89,   82,   92,
       92,  112,   92,   95,   95,   89,   98,  116,   81,   81,
       89,   96,  116,  109,   92,   95,   81,   95,   81,   83,
       83,   98,   83,  101,   96,  102,  102,  108,  110,  110,
       83,  109,  111,  111,  101,   83,  114,  102,  108,  102,
      115,  115,  115,   83,  115,  114,  101,  101,  133,  118,

      135,  108,  123,  123,  141,  124,   83,   90,   90,  135,
       90,  133,   90,  118,  120,  120,  120,  141,  120,  126,
      126,  142,   90,  124,  130,  130,  131,  131,   90,   90,
      132,  132,  143,  158,  142,  160,   90,  125,   90,  134,
      134,  164,  134,  146,  134,  158,  143,  160,  134,  134,
      134,  134,  134,  164,  134,  134,  146,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  136,  136,  157,
      136,  147,  136,  170,  170,  122,  136,  121,  119,  136,
      157,  113,  136,  107,  147,  136,  136,  136,  136,  136,

      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  137,  137,  167,  137,  152,
      137,  177,   97,   88,  137,  137,  137,  137,  177,  167,
      137,  137,  152,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  144,  144,  153,  144,  163,  165,
      156,  166,  159,  144,  144,  144,  161,  168,  169,  153,
      144,  154,  154,  156,  154,  159,  172,  165,  176,  161,
      169,  163,  154,  154,  166,  178,   85,  154,  172,   78,
      168,   75,  178,   74,  176,  180,  180,   72,  180,  180,

       67,  180,   66,  180,  180,  180,  181,  181,  181,  181,
      181,   65,  181,  181,  181,  181,  181,  182,   64,   63,
       61,   60,  182,  182,   50,   48,  182,  183,  183,   47,
      183,   46,   45,  183,   40,   34,  183,  183,  184,   28,
       24,  184,  185,   20,   13,    7,    3,    0,  185,    0,
        0,  185,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  188,    0,    0,    0,    0,
        0,    0,  188,    0,    0,  188,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  190,
        0,    0,  190,  191,    0,    0,  191,  192,    0,    0,

      192,  193,  193,    0,  193,    0,    0,  193,  194,  194,
      194,  194,  194,    0,  194,  195,    0,    0,  195,  196,
      196,  196,  196,    0,    0,  196,  196,  197,    0,    0,
      197,  198,    0,    0,  198,  199,  199,    0,  199,    0,
        0,  199,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokenizer.flex"
#define INITIAL 0
/*Tokenizer lex: tokenizes keywords from an HTML file*/
#line 4 "tokenizer.flex"
#include <iostream>
#include <ctype.h>
#include <string.h>
#include <dirent.h>
#include "hashtable.h"
#include "invertedFile.h"
#include <time.h>
#include <bits/stdc++.h>
extern int yylex(void);
using namespace std;
using std::tolower;
#undef yywrap

char Ch;
const int SIZE = 60000;
HashTable ht(3*SIZE);
string Prevname = "";
int numOfTotalTokens = 0;
bool currNewLine = false;
HashTable ght(SIZE);
int docID = 0;
float numOfLogDocTokens[SIZE];
int numOfDocsIn[1000];
bool stopListInit = true;
const int STOPLISTSIZE = 150;
HashTable stopList(3*STOPLISTSIZE);

const int MAXFILESOPEN = 1000;
const int MAXFILESTOTAL = 100000;
//Note that MAXFILESTOTAL is much larger than MAXFILESOPEN. The current distro of Linux that Turing runs on only allows ~1,000 files
//open at the same time. Since the buffer relies on the alphabetical order of the tokens, it is necessary to switch between the first
//1000ish files of the filePtrs, then switch to the next 1000, and so on.
struct FILEANDNAME{
        FILE* fileptr = nullptr;
        string filename = "";
};
FILEANDNAME filePtrs[MAXFILESTOTAL];
struct fileInfo{
        string term = "";
        float weight = 0;
        int fileID = -1;
};
fileInfo buffer[MAXFILESOPEN][MAXFILESTOTAL/MAXFILESOPEN + 1];

//used for non-general downcasing
char* Downcase(const char* input){
        char* result = (char*)malloc(strlen(input) + 1);
	if(result == NULL){
		return NULL;
	}
	int i = 0;
	while(input[i] != '\0'){
		if (isalpha(input[i])) {
            		result[i] = tolower(input[i]);
        	} else {
            		result[i] = input[i]; //Copy non-alphabetic characters as is
        	}
        	i++;
    	}
 	result[i] = '\0'; // Null-terminate the result string
    	return result;
}

void tokenize(string text){
	int data = ht.GetData(text);
	if(data != -1){
		currNewLine = true;
	}
	if(text == "\n"){
		currNewLine = true;
	}else{
		if(text.length() > 1){
			if(stopListInit && (stopList.GetData(text) != -1)){
				return;
			}
			bool unique = false;
			data = ht.GetData(text);
        		if(data == -1){
				unique = true;
        		}
			numOfTotalTokens++;
			currNewLine = false;
			ht.Insert(text, 1, 0, (unique ? 1 : 0));
			ght.Insert(text, 1, 0, (unique ? 1 : 0));
		}
	}
}

void ProcessHashtable(){
	fprintf(yyout, "%s", (ht.Print(docID)).c_str());
	numOfLogDocTokens[docID] = ht.CalculateTotalLog();
	ht.Clear();
	docID++;
}

void openClusterFiles(size_t index){
        const char* currFilename;
        for(size_t i = index*MAXFILESOPEN; i < (index+1)*MAXFILESOPEN; i++){
                currFilename = filePtrs[i].filename.c_str();
                if(strcmp(currFilename, "") != 0){
                        filePtrs[i].fileptr = fopen(currFilename, "r");
                }
        }
}

void closeClusterFiles(size_t index){
	cout << "D" << endl;
        const char* currFilename;
        for(size_t i = index*MAXFILESOPEN; i < (index+1)*MAXFILESOPEN; i++){
		cout << i << " " << filePtrs[i].filename << " " << filePtrs[i].fileptr << endl;
		currFilename = filePtrs[i].filename.c_str();
		cout << "A" << endl;
                if(strcmp(currFilename, "") != 0){
                        cout << "B: " << filePtrs[i].fileptr << " " << (filePtrs[i].fileptr != nullptr) << endl;
			if (ferror(filePtrs[i].fileptr)){
				fprintf(stderr, "Error occurred while reading file: %s\n", strerror(errno));
			}
			fclose(filePtrs[i].fileptr);
			cout << "C" << endl;
                }
        }
}

#line 702 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 145 "tokenizer.flex"

#line 866 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 180 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 643 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 146 "tokenizer.flex"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 148 "tokenizer.flex"
{char* lowered = Downcase(yytext); if (lowered != NULL){ tokenize(lowered); free(lowered); }}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 150 "tokenizer.flex"
{tokenize(yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 152 "tokenizer.flex"
;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 154 "tokenizer.flex"
{tokenize(yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 156 "tokenizer.flex"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 158 "tokenizer.flex"
{tokenize("\n");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 160 "tokenizer.flex"
{tokenize(yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 162 "tokenizer.flex"
{char* lowered = Downcase(yytext); if (lowered != NULL){ tokenize(lowered); free(lowered); }}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 164 "tokenizer.flex"
;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 165 "tokenizer.flex"
ECHO;
	YY_BREAK
#line 1004 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 180 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 180 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 179);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 165 "tokenizer.flex"


//global variables for the input directory pointer
//and output directory name for use in yywrap
DIR *InputDirPtr = NULL;
string InDirname;
string OutDirname;
string OutFilename;
string InFilename;
bool OutputFileIsOpen = false;
InvertedFile IV;

// This is called once per file.
int yywrap(){
	struct dirent* InputDirEntryPtr;

	//if there was an input file open 
	//close it to get ready for the next file 
	if (yyin != NULL){
      		fclose(yyin);
      		yyin = NULL;
      		//Just closed the file
		ProcessHashtable();
   	}

   	//if there was an output file open
   	//close it to get ready for the next file 
   	if (OutputFileIsOpen){
		fclose(yyout);
      		OutputFileIsOpen = false;
   	}

   	//skip over the hidden filenames that begin with dot
   	do{
      		InputDirEntryPtr = readdir(InputDirPtr);
   	} while ((InputDirEntryPtr != NULL) && (InputDirEntryPtr->d_name[0] == '.'));

   	//if there are still files to process
   	if(InputDirEntryPtr != NULL){
		//open the next file in the list as yyin
      		InFilename = InDirname + '/'+ InputDirEntryPtr->d_name;
		if(docID <= MAXFILESTOTAL - 1){
			yyin = fopen(InFilename.c_str(), "r");
		
      			//if file open failed, print an error
      			if(yyin == NULL){ 
         			perror(InFilename.c_str());
			}

			//Only needed if doing Multiway Merge (creates temporary token files)

      			//open a matching output file and set it to yyout
      			OutFilename = OutDirname + '/' + InputDirEntryPtr->d_name;
			yyout = fopen(OutFilename.c_str(), "w");	
      			// if file open failed, print an error
      			if(yyout == NULL){ 
         			perror(OutFilename.c_str());
      			}else{
          			OutputFileIsOpen = true;
   			}
		}
	}

	//if yyin is NULL, return 1, else return 0
   	return (yyin == NULL);
}

int main(int argc, char **argv){
	clock_t start, end;
	start = clock();
        FILE* stopFile = fopen("stopList.txt", "r");
        if (stopFile == nullptr) {
        	perror("Error opening stopList file! Stop words will not be considered!");
        	stopListInit = false;
    	}
	if(stopListInit){
		char buffer[125];
		while (fgets(buffer, sizeof(buffer), stopFile) != nullptr) {
			size_t length = strcspn(buffer, "\n");
        		buffer[length] = '\0';
			stopList.Insert(buffer, 1);
    		}
		fclose(stopFile);
	}
	DIR *OutputDirPtr = NULL;
	if(argc != 3){
		cout << "\n Incorrect number of arguments. Make sure to have input and output file. \n";
		return(1);
	}
	
	InDirname = argv[1];
	OutDirname = argv[2];
	InputDirPtr = opendir(InDirname.c_str());
	
	if (!InputDirPtr){
		cerr << "Unable to open input directory: " << InDirname << "\n";
	}else{
		//open or create output dir
		OutputDirPtr = opendir(OutDirname.c_str());
		if(!OutputDirPtr){
			string cmd = "mkdir -p " + OutDirname;
			system(cmd.c_str());
			OutputDirPtr = opendir(OutDirname.c_str());
		}
		
		//init input and output file ptrs
		yyin = NULL;
		yyout = NULL;

		//process files
		yywrap();
		yylex();

		//close input and output dir
		(void) closedir(InputDirPtr);

		struct dirent* OutputEntryPtr = readdir(OutputDirPtr);
		IV.openForWrite();

		unsigned int numFiles = 0;
		while(OutputEntryPtr != NULL && numFiles < MAXFILESTOTAL){
			if(OutputEntryPtr->d_name[0] != '.'){
				string filename = OutDirname + '/' + OutputEntryPtr->d_name;
				filePtrs[numFiles].filename = filename.c_str();
				IV.writeMapRecord(numFiles, OutputEntryPtr->d_name);
				numFiles = (numFiles >= MAXFILESTOTAL) ? MAXFILESTOTAL : numFiles + 1;
			}
			OutputEntryPtr = readdir(OutputDirPtr);
		}
		openClusterFiles(0);
		bool finished = false;

		string currTerm = "";
                string minTerm = "";
                int currFreq = 0;
                for(size_t i = 0; i < numFiles/MAXFILESOPEN + 1; i++){
			if(i != 0){
				closeClusterFiles(i-1);
				openClusterFiles(i);
			}
			for(size_t j = 0; j < MAXFILESOPEN; j++){
				int currID = 0;
                        	char tmp[256];
                        	if(buffer[j][i].term == ""){
					if(i*MAXFILESOPEN+j < numFiles && !feof(filePtrs[i*MAXFILESOPEN+j].fileptr)){
						fscanf(filePtrs[i*MAXFILESOPEN+j].fileptr, "%s %d %d", tmp, &currID, &currFreq);
                                		int cluster = currID/MAXFILESOPEN; int position = currID%MAXFILESOPEN;
						currTerm = tmp;
						//cout << "buffer[" << position << "][" << cluster << "]: " << currTerm << endl;
                                		buffer[position][cluster].term = currTerm;
						buffer[position][cluster].weight = (1 + log(currFreq))/numOfLogDocTokens[currID];
						buffer[position][cluster].fileID = i;
					}else{
                                		buffer[j][i].term = ""; buffer[j][i].weight = 0;
                                	}
                        	}else{
					int cluster = currID/MAXFILESOPEN; int position = currID%MAXFILESOPEN;
					currTerm = buffer[position][cluster].term;
                        	}
			}
                }	
		while (!finished) {
			cout << "C" << endl;
			minTerm = "";

		    	for(size_t i = 0; i < numFiles/MAXFILESOPEN + 1; i++){
				for(size_t j = 0; j < MAXFILESOPEN; j++){
					//cout << "buffer[" << j << "][" << i << "].term " << buffer[j][i].term << endl;
					if (buffer[j][i].term != "" && (minTerm == "" || buffer[j][i].term < minTerm)) {
			    			cout << j << " " << i << " " << buffer[j][i].term;
						minTerm = buffer[j][i].term;
					}
		    		}
			}

		    	if (minTerm == ""){
				finished = true;
		    	}else{
				int totalFreq = 0;
				bool emptyFlag = true;
				for(size_t i = 0; i < numFiles/MAXFILESOPEN + 1; i++){
					for(size_t j = 0; j < MAXFILESOPEN; j++){
                                        	if((minTerm != "") && (buffer[j][i].term == minTerm) && (!feof(filePtrs[buffer[j][i].fileID].fileptr))){
							totalFreq += 1;
						}
					}
				}

				for(size_t i = 0; i < numFiles/MAXFILESOPEN + 1; i++){
					if(i != 0){
                                		cout << "A: " << i << endl;
						closeClusterFiles(i-1);
						cout << "B" << endl;
                                		openClusterFiles(i);
						cout << "C" << endl;
                        		}
					for(size_t j = 0; j < MAXFILESOPEN; j++){
						fileInfo currFile = buffer[j][i];
						cout << i << " " << j << " " << currFile.term << endl;
						if ((minTerm != "") && (buffer[j][i].term == minTerm) && (!feof(filePtrs[currFile.fileID].fileptr))) {
							cout << currFile.term << " " << currFile.weight << endl;
							IV.writePostRecord(i*MAXFILESOPEN + j, (1 + log(numFiles/totalFreq))*currFile.weight);
							char tmp[256];
							int currID;

							if (i*MAXFILESOPEN + j < numFiles && !feof(filePtrs[currFile.fileID].fileptr)) {
								fscanf(filePtrs[currFile.fileID].fileptr, "%s %d %d", tmp, &currID, &currFreq);
				    				currTerm = tmp;
				    				buffer[j][i].term = currTerm; buffer[j][i].weight = (1 + log(currFreq))/numOfLogDocTokens[currID];
								//cout << tmp << ": " << setw(12) << numOfLogDocTokens[currID] << "; " << setw(15) << buffer[currID].weight << endl;
								emptyFlag = false;
							}else{
				    				buffer[j][i].term = "";
				    				buffer[j][i].weight = 0;
							}
			    			}else if((i*MAXFILESOPEN + j < numFiles && feof(filePtrs[currFile.fileID].fileptr))){
							buffer[j][i].term = "";
                                		}
					}
				}
				if(!emptyFlag){
					if(ght.UpdateStart(minTerm, start)){
						start += totalFreq;
					}
				}
			}
		}	

		ght.PrintDict(IV, true);
		IV.closeAfterWriting();
		(void) closedir(OutputDirPtr);
	}

	end = clock();
	double totalTime = double(end - start)/double(CLOCKS_PER_SEC);
	cout << "TOOK " << totalTime << " SECONDS";
	//FILE* config = fopen("config.txt", "w");
	//fprintf(config, "%d\n", 3*SIZE);
	//fclose(config);
	//stopList.Print("TESTINGFILE.txt");
	
	cout << "\nTOTAL TOKENS: " << numOfTotalTokens << "\n";
	cout << "Done tokenizing. Good place to write the dict and post files.\n";
}
